/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { convertMsToMmSs } from './utils/timeUtils';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
    // Return false to exempt requests from being fulfilled by index.html.
    ({ request, url }: { request: Request; url: URL }) => {
        // If this isn't a navigation, skip.
        if (request.mode !== 'navigate') return false;

        // If this is a URL that starts with /_, skip.
        if (url.pathname.startsWith('/_')) return false;

        // If this looks like a URL for a resource, because it contains
        // a file extension, skip.
        if (url.pathname.match(fileExtensionRegexp)) return false;

        // Return true to signal that we want to use the handler.
        return true;
    },
    createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
    // Add in any other file extensions or routing criteria as needed.
    ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
    // Customize this strategy as needed, e.g., by changing to CacheFirst.
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            // Ensure that once this runtime cache reaches a maximum size the
            // least-recently used images are removed.
            new ExpirationPlugin({ maxEntries: 50 }),
        ],
    })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
// Any other custom service worker logic can go here.
type TimerHandles = { timeoutId: NodeJS.Timeout | undefined; intervalId: NodeJS.Timer | undefined };

const timers: Record<string, TimerHandles> = {};
const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent);

/** Wall-clock based remaining ms; do not use interval delta (setInterval is throttled in background). */
const NOTIFICATION_TICK_MS = 1000;
/** Stop updating the notification this long after the timer ended (battery / spam guard). */
const OVERTIME_CAP_MS = 10 * 60 * 1000;

const clearTimerHandles = (timerId: string) => {
    const handles = timers[timerId];
    if (handles) {
        clearTimeout(handles.timeoutId);
        clearInterval(handles.intervalId);
        delete timers[timerId];
    }
};

self.addEventListener('message', (event) => {
    if (event.source) {
        const clientId = (event.source as Client).id;
        const { command, timer, endTime } = event.data;

        if (command === 'start-timer') {
            const endTimeMs = Number(endTime);
            clearTimerHandles(timer.id);

            const remainingTime = Math.max(0, endTimeMs - Date.now());
            console.debug(`Starting timer with ID: ${timer.id}, Remaining time: ${remainingTime}ms`);

            let timeoutId: NodeJS.Timeout | undefined;
            if (remainingTime > 0) {
                timeoutId = setTimeout(async () => {
                    const clientList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
                    const targetClient = clientList.find((client) => client.id === clientId);

                    if (targetClient) {
                        targetClient.postMessage({ command: 'finished', id: timer.id });
                    }
                }, remainingTime);
            }

            let intervalId: NodeJS.Timer | undefined;
            if (isIOS) {
                self.registration.showNotification(timer.title, {
                    body: 'Timer is currently running in the background',
                    icon: '/visual-timer/logo512.png',
                    tag: timer.id,
                    silent: true,
                });
            } else {
                let intervalHandle: NodeJS.Timer | undefined;
                const tick = async () => {
                    const rawMs = endTimeMs - Date.now();

                    if (rawMs < -OVERTIME_CAP_MS) {
                        if (intervalHandle !== undefined) {
                            clearInterval(intervalHandle);
                            intervalHandle = undefined;
                        }
                        const handles = timers[timer.id];
                        if (handles) {
                            handles.intervalId = undefined;
                        }
                        return;
                    }

                    await self.registration.showNotification(timer.title, {
                        body: convertMsToMmSs(rawMs),
                        icon: '/visual-timer/logo512.png',
                        tag: timer.id,
                        silent: true,
                    });
                };

                void tick();
                intervalHandle = setInterval(() => {
                    void tick();
                }, NOTIFICATION_TICK_MS);
                intervalId = intervalHandle;
            }

            timers[timer.id] = { timeoutId, intervalId };
        } else if (command === 'clear-timer') {
            console.debug(`Clearing timer with ID: ${timer.id}`);
            clearTimerHandles(timer.id);

            const clearAllRelatedNotifications = async () => {
                while ((await self.registration.getNotifications({ tag: timer.id })).length > 0) {
                    const notifications = await self.registration.getNotifications({ tag: timer.id });
                    notifications.forEach((notification) => notification.close());
                }
            };

            clearAllRelatedNotifications();
        } else {
            console.warn(`Unknown command: ${command}`);
        }
    }
});

const navigateToApp = async () => {
    const clientList = await self.clients.matchAll({
        type: 'window',
        includeUncontrolled: true,
    });

    const hadClientOpen = clientList.some((client) => {
        if (client.url.includes('/visual-timer') && 'focus' in client) return client.focus();
        return false;
    });

    if (!hadClientOpen && self.clients.openWindow) {
        await self.clients.openWindow('/visual-timer');
    }
};

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(navigateToApp());
});
