/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import {
    createFinishedNotification,
    createRunningStatusNotification,
    type TimerFinishedPayload,
} from './utils/timerNotificationPayload';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all assets generated by Vite build process
precacheAndRoute(self.__WB_MANIFEST);

// SPA App Shell routing for navigation requests
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
}, createHandlerBoundToURL('/visual-timer/index.html'));

// Cache images
registerRoute(
    ({ url }) =>
        url.origin === self.location.origin &&
        (url.pathname.endsWith('.png') || url.pathname.endsWith('.ico') || url.pathname.endsWith('.svg')),
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 })],
    })
);

// Cache audio assets
registerRoute(
    ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.mp3'),
    new CacheFirst({
        cacheName: 'audio-cache',
        plugins: [new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 24 * 60 * 60 })],
    })
);

// Skip waiting on demand
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

self.addEventListener('message', (event) => {
    const { command, timerId, title, endAt } = event.data || {};
    if (!timerId) return;

    if (command === 'show-running-status' && title && Number.isFinite(endAt)) {
        const notification = createRunningStatusNotification(timerId, title, Number(endAt));
        event.waitUntil(self.registration.showNotification(notification.title, notification.options));
    }

    if (command === 'clear-running-status') {
        event.waitUntil(
            self.registration.getNotifications({ tag: `running-${timerId}` }).then((notifications) => {
                notifications.forEach((notification) => notification.close());
            })
        );
    }
});

const navigateToApp = async (deepLink = '/visual-timer/') => {
    const clientList = await self.clients.matchAll({
        type: 'window',
        includeUncontrolled: true,
    });

    for (const client of clientList) {
        if (client.url.includes('/visual-timer') && 'focus' in client) {
            await (client as WindowClient).focus();
            return;
        }
    }

    if (self.clients.openWindow) {
        await self.clients.openWindow(deepLink);
    }
};

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(navigateToApp(event.notification.data?.deepLink));
});

self.addEventListener('push', (event) => {
    const payload = event.data?.json() as (TimerFinishedPayload & { type: 'timer-finished' }) | undefined;
    if (!payload || payload.type !== 'timer-finished') return;

    const notification = createFinishedNotification(payload);
    event.waitUntil(self.registration.showNotification(notification.title, notification.options));
});
